// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/packages": {
    params: {};
  };
  "/solar-calculator": {
    params: {};
  };
  "/client-journey": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/dev-admin": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects" | "/projects/:id" | "/packages" | "/solar-calculator" | "/client-journey" | "/sitemap.xml" | "/*" | "/dev-admin" | "/robots.txt";
  };
  "layouts/main-layout.tsx": {
    id: "layouts/main-layout";
    page: "/" | "/projects" | "/projects/:id" | "/packages" | "/solar-calculator" | "/client-journey" | "/sitemap.xml" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/projects._index.tsx": {
    id: "routes/projects._index";
    page: "/projects";
  };
  "routes/projects.$id.tsx": {
    id: "routes/projects.$id";
    page: "/projects/:id";
  };
  "routes/packages.tsx": {
    id: "routes/packages";
    page: "/packages";
  };
  "routes/solar-calculator.tsx": {
    id: "routes/solar-calculator";
    page: "/solar-calculator";
  };
  "routes/client-journey.tsx": {
    id: "routes/client-journey";
    page: "/client-journey";
  };
  "routes/sitemap-xml.tsx": {
    id: "routes/sitemap-xml";
    page: "/sitemap.xml";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/dev-admin";
  };
  "routes/robots-txt.tsx": {
    id: "routes/robots-txt";
    page: "/robots.txt";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/main-layout": typeof import("./app/layouts/main-layout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/projects._index": typeof import("./app/routes/projects._index.tsx");
  "routes/projects.$id": typeof import("./app/routes/projects.$id.tsx");
  "routes/packages": typeof import("./app/routes/packages.tsx");
  "routes/solar-calculator": typeof import("./app/routes/solar-calculator.tsx");
  "routes/client-journey": typeof import("./app/routes/client-journey.tsx");
  "routes/sitemap-xml": typeof import("./app/routes/sitemap-xml.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/robots-txt": typeof import("./app/routes/robots-txt.tsx");
};