/**
 * https://azari.solar/sitemap.xml — the public sitemap URL referenced by
 * robots.txt and submitted to Search Console.
 *
 * The document itself is generated by azari-service, which queries the database
 * directly and filters to published projects. This route only forwards it, so
 * there is one generator rather than two implementations drifting apart on
 * priorities and lastmod values.
 *
 * The backend's own path lives under /api, which nginx marks noindex and
 * no-store, so it is not suitable as the advertised sitemap URL.
 */

const API_BASE = process.env["API_URL"] ?? "http://localhost:4000";

const BASE_URL = "https://azari.solar";

// Served only if the API cannot be reached, so crawlers still get the static
// pages instead of an error. Keep in step with STATIC_PAGES in
// azari-service/src/routes/sitemap.routes.ts.
const FALLBACK_PAGES = [
  { path: "/", priority: "1.0", changefreq: "weekly", lastmod: "2026-08-20" },
  { path: "/projects", priority: "0.9", changefreq: "weekly", lastmod: "2026-08-20" },
  { path: "/packages", priority: "0.8", changefreq: "monthly", lastmod: "2026-08-20" },
  { path: "/solar-calculator", priority: "0.8", changefreq: "monthly", lastmod: "2026-08-20" },
  { path: "/client-journey", priority: "0.7", changefreq: "monthly", lastmod: "2026-08-20" },
  { path: "/privacy-policy", priority: "0.3", changefreq: "yearly", lastmod: "2026-08-20" },
  { path: "/terms-and-conditions", priority: "0.3", changefreq: "yearly", lastmod: "2026-08-20" },
];

function fallbackSitemap(): string {
  const entries = FALLBACK_PAGES.map(
    (p) =>
      `  <url>\n` +
      `    <loc>${BASE_URL}${p.path}</loc>\n` +
      `    <lastmod>${p.lastmod}</lastmod>\n` +
      `    <changefreq>${p.changefreq}</changefreq>\n` +
      `    <priority>${p.priority}</priority>\n` +
      `  </url>`,
  ).join("\n");

  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${entries}\n` +
    `</urlset>`
  );
}

export async function loader() {
  let xml: string | null = null;

  try {
    const res = await fetch(`${API_BASE}/api/sitemap.xml`, {
      headers: { Accept: "application/xml" },
    });
    if (res.ok) {
      const body = await res.text();
      if (body.trimStart().startsWith("<?xml")) xml = body;
    }
  } catch {
    // fall through to the static fallback below
  }

  return new Response(xml ?? fallbackSitemap(), {
    status: 200,
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
