/**
 * Keeps nginx's Content-Security-Policy for prerendered pages in step with
 * the app's policy (app/lib/security/site-policy.ts).
 *
 *   node scripts/audit-csp.ts          check nginx.conf and, if present, build/
 *   node scripts/audit-csp.ts --write  regenerate the block in nginx.conf
 *
 * nginx serves prerendered pages straight from disk, so it sets their CSP
 * headers itself, with $request_id standing in for the nonce. The check also
 * confirms every script in the prerendered HTML carries the placeholder
 * nonce that nginx rewrites.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

import { CspNonce } from "../app/lib/security/content-security-policy.ts";
import { PrerenderNonceSource } from "../app/lib/security/nonce.server.ts";
import { EnforcedSitePolicy, ReportOnlySitePolicy } from "../app/lib/security/site-policy.ts";

const NGINX_CONF = "nginx.conf";
const PRERENDER_ROOT = join("build", "client");
const BEGIN = "# BEGIN generated by scripts/audit-csp.ts --write; do not edit by hand";
const END = "# END generated CSP";
const NGINX_NONCE = "$request_id";

function nginxBlock(): string {
  const placeholder = new CspNonce(PrerenderNonceSource.PLACEHOLDER);
  const enforced = new EnforcedSitePolicy().build().toString();
  const reportOnly = new ReportOnlySitePolicy(placeholder)
    .build()
    .toString()
    .replace(PrerenderNonceSource.PLACEHOLDER, NGINX_NONCE);
  const map = (name: string, value: string) =>
    [`map $uri ${name} {`, `    "~/index\\.html$" "${value}";`, `    default "";`, `}`].join("\n");
  return [
    BEGIN,
    map("$azari_csp", enforced),
    map("$azari_csp_report_only", reportOnly),
    END,
  ].join("\n");
}

function currentBlock(conf: string): string | undefined {
  const start = conf.indexOf(BEGIN);
  const end = conf.indexOf(END);
  return start === -1 || end === -1 ? undefined : conf.slice(start, end + END.length);
}

function htmlFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return htmlFiles(path);
    return entry.name === "index.html" ? [path] : [];
  });
}

/** Script tags that would run, i.e. not JSON-LD or other data blocks. */
function scriptsWithoutPlaceholder(html: string): string[] {
  const tags = html.match(/<script\b[^>]*>/g) ?? [];
  return tags.filter(
    (tag) =>
      !/type="application\/(ld\+)?json"/.test(tag) &&
      !tag.includes(`nonce="${PrerenderNonceSource.PLACEHOLDER}"`),
  );
}

const conf = readFileSync(NGINX_CONF, "utf8");
const expected = nginxBlock();
const actual = currentBlock(conf);

if (process.argv.includes("--write")) {
  if (actual === undefined) {
    console.error(`${NGINX_CONF}: markers not found; add "${BEGIN}" and "${END}" first`);
    process.exit(1);
  }
  writeFileSync(NGINX_CONF, conf.replace(actual, expected));
  console.log(`${NGINX_CONF}: CSP block regenerated`);
  process.exit(0);
}

const problems: string[] = [];
if (actual !== expected) {
  problems.push(`${NGINX_CONF}: CSP block is out of date; run "npm run csp:nginx"`);
}
if (existsSync(PRERENDER_ROOT)) {
  for (const file of htmlFiles(PRERENDER_ROOT)) {
    for (const tag of scriptsWithoutPlaceholder(readFileSync(file, "utf8"))) {
      problems.push(`${file}: script without the prerender nonce: ${tag.slice(0, 120)}`);
    }
  }
}

if (problems.length > 0) {
  for (const problem of problems) console.error(problem);
  process.exit(1);
}
console.log("CSP: nginx block matches the app policy; prerendered scripts carry the nonce placeholder");
